---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users":
    get:
      summary: list users
      tags:
      - Users
      responses:
        '200':
          description: successful
    post:
      summary: Creates a user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                tax_id:
                  type: string
              required:
              - name
              - tax_id
            examples:
              '201':
                summary: 201_response
                value:
                  name: Kilder
                  tax_id: 31.576.685/0001-42
              '422':
                summary: 422_response
                value:
                  name: Kilder
  "/api/v1/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      tags:
      - Users
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example_key:
                  value:
                    user:
                      id: 1
                      name: Kilder
                      tax_id: 31.576.685/0001-42
    put:
      summary: update user
      tags:
      - Users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                tax_id:
                  type: string
              required:
              - name
              - tax_id
    delete:
      summary: delete user
      tags:
      - Users
      responses:
        '204':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
